github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
future: true
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-dinky
# docs at https://github.com/pages-themes/dinky/
plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-avatar

title: SwiftUI Notes
description: Notes on using SwiftUI and Combine
show_downloads: true
google_analytics: UA-898243-5
